// The signifier of an API call
export const CALL_API = 'CALL_API';

// AUTH types

export const CLEAR_AUTH = 'CLEAR_AUTH';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';

export const SAVE_REFRESH_TOKEN_PROMISE = 'SAVE_REFRESH_TOKEN_PROMISE';
export const CLEAR_REFRESH_TOKEN_PROMISE = 'CLEAR_REFRESH_TOKEN_PROMISE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

// artefact

export const REGISTER_ARTEFACT_REQUEST = 'REGISTER_ARTEFACT_REQUEST';
export const REGISTER_ARTEFACT_SUCCESS = 'REGISTER_ARTEFACT_SUCCESS';
export const REGISTER_ARTEFACT_FAILURE = 'REGISTER_ARTEFACT_FAILURE';

export const GET_ALL_ARTIFACTS_REQUEST = 'GET_ALL_ARTIFACTS_REQUEST';
export const GET_ALL_ARTIFACTS_SUCCESS = 'GET_ALL_ARTIFACTS_SUCCESS';
export const GET_ALL_ARTIFACTS_FAILURE = 'GET_ALL_ARTIFACTS_FAILURE';

export const GET_ARTIFACT_REQUEST = 'GET_ARTIFACT_REQUEST';
export const GET_ARTIFACT_SUCCESS = 'GET_ARTIFACT_SUCCESS';
export const GET_ARTIFACT_FAILURE = 'GET_ARTIFACT_FAILURE';

export const RESET_ARTIFACT = 'RESET_ARTIFACT';

// group

export const REGISTER_GROUP_REQUEST = 'REGISTER_GROUP_REQUEST';
export const REGISTER_GROUP_SUCCESS = 'REGISTER_GROUP_SUCCESS';
export const REGISTER_GROUP_FAILURE = 'REGISTER_GROUP_FAILURE';

export const GET_ALL_GROUPS_REQUEST = 'GET_ALL_GROUPS_REQUEST';
export const GET_ALL_GROUPS_SUCCESS = 'GET_ALL_GROUPS_SUCCESS';
export const GET_ALL_GROUPS_FAILURE = 'GET_ALL_GROUPS_FAILURE';

export const GET_GROUP_REQUEST = 'GET_GROUP_REQUEST';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE';

// resource

export const POST_ARTIFACT_RESOURCE_REQUEST = 'POST_ARTIFACT_RESOURCE_REQUEST';
export const POST_ARTIFACT_RESOURCE_SUCCESS = 'POST_ARTIFACT_RESOURCE_SUCCESS';
export const POST_ARTIFACT_RESOURCE_FAILURE = 'POST_ARTIFACT_RESOURCE_FAILURE';
